services:
  proxy-app:
    image: traefik:latest
    container_name: ${STACK_NAME}-app
    network_mode: host
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:${HTTP_PORT:-8080}
      - --entrypoints.websecure.address=:${HTTPS_PORT:-8443}
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      # - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --api.dashboard=true
      - --ping=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${STACK_NAME}-letsencrypt:/letsencrypt
      - ${DYNAMIC_DIR}:/dynamic:ro   # <- host path from .env

    labels:
      - traefik.enable=true

volumes:
  ${STACK_NAME}-letsencrypt:
    name: ${STACK_NAME}-letsencrypt
    driver: local
